name: easy_audio_trimmer
description: A Flutter package for trimming audio. This supports retrieving, trimming, and storage of trimmed audio files to the file system.
version: 2.0.1+1
homepage: https://github.com/mayurpitroda96/easy_audio_trimmer

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.4.0
  ffmpeg_kit_flutter_new: ^1.1.0
  intl: ^0.19.0
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
